[tool.poetry]
name = "tweet_sentiment_extraction"
version = "0.1.0"
description = ""
authors = ["Vinh Pham-Gia <vinhpg45@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.0.3"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
